### ISSUE TITLE
Rework `prefetch`

### ISSUE THREAD

**Issue by Bolodya1997** [networkservicemesh/integration-tests#864]
## Description
Currently we are facing several issues with existing `prefetch`:
1. It looks only in `app` directory.
2. It doesn't follow URLs, so if we are using some remote deployment, no images would be loaded for it.
3. It requires `containerd` to be on cluster nodes.
4. It doesn't work for interdomain scenario.

### Looking for images
1. Start in `deployments-k8s` root directory.
2. For all files in directory - if file contain `image: ` or `https://`, add it to `files`. <--[*]
3. For all directories in directory do [*].
4. For all files in `files`:
   1. file contain `image: `.
      1. Add image to `images` map.
   2. file contain `https://`.
      1. Check if we already have such URL processed. <--[**]
      2. URL is a file URL.
         1. Fetch file, add to `files`.
      3. URL is a directory URL.
         1. Fetch `URL/kustomize.yaml` file.
         2. Transform every resource, base line to `URL/line`.
         3. For every transformed line do [**].

### Fetching images
1. For each `KUBECONFIG` from `$KUBECONFIGn` do:
2. For each container create a daemonset:
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fetch-${image}
  labels:
    app: fetch-${image}
spec:
  selector:
    matchLabels:
      app: fetch-${image}
  template:
    metadata:
      labels:
        app: fetch-${image}
    spec:
      containers:
        - image: ${image}:tag
          imagePullPolicy: IfNotPresent
          name: fetch-${image}
          command: [] # <-- TODO: think about something more clever
```
3. Start it and wait with `kubectl rollout status daemonset/...`.
